### ISSUE TITLE
Can't execute nothing after installing DeployBundle

### ISSUE THREAD

**Issue by QuingKhaos** [hpatoio/DeployBundle#1]
After installing the DeployBundle with composer I can't execute no command with the symfony console. Regardless of which command I try, following exception is thrown:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
The path "deploy" should have at least 1 element(s) defined.
```

This exception is also thrown in the development-env (app_dev.php)

Environment: Symfony v2.1.7 Standard Distribution plus FOSUserBundle v1.3.1

**Comment by mediavince** [comment]
FYI the link provided issues a 404
Here is the proper config link:
https://github.com/hpatoio/DeployBundle/blob/master/README.md

**Comment by hpatoio** [comment]
Sure. That was an old one !
