### ISSUE TITLE
Your bitly repo

### ISSUE THREAD

**Issue by phplicengine** [hpatoio/DeployBundle#16]
Hi @hpatoio 
I could not open an issue on your bitly github. Wanted to say as you abandoned your bitly repo. We are grateful if you add a link to our bitly repo as replacement suggestion.
Thanks,

**Comment by hpatoio** [comment]
See last 2 commits here https://github.com/hpatoio/bitly-api/commits/master

**Comment by phplicengine** [comment]
Thanks a lot.
